version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
    - image: circleci/android:api-28
    environment:
      JVM_OPTS: -Xmx3200m
      CC_TEST_REPORTER_ID: bb10b50d328a7320f3ed14674a6eab68eac9385e0c3617d15de8b3af1967837d
      ADB_INSTALL_TIMEOUT: 60
    steps:
    - checkout
    - restore_cache:
        key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
    - run:
        name: Download Dependencies
        command: ./gradlew androidDependencies
    - save_cache:
        paths:
        - ~/.gradle
        key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
    - store_artifacts:
        path: app/build/reports
        destination: reports
    - store_test_results:
        path: app/build/test-results
    - run:
        name: Run Build
        command: ./gradlew build
    - store_artifacts:
        path: app/build/outputs/apk/debug/
        destination: artifact-file
