# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself

fastlane_require 'dotenv'

update_fastlane


default_platform(:android)

platform :android do
    fastlane_require 'dotenv'

  before_all do
    Dotenv.overload '.env.secret'
    # Loaded from .env (by fastlane)
      puts "SLACK_URL: #{ENV['SLACK_URL']}"
   end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to slack"
  lane :slackbuild do
    gradle(task: "assembleRelease")
    slack(message: "Build Successful!")
    upload_to_slack()
  end

    # Add this to your Fastfile
    desc "Upload the APK to Slack channel"
    private_lane :upload_to_slack do |options|
      file_path = lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH]
      file_name = file_path.gsub(/\/.*\//,"")
      token = ENV['SLACK_API_TOKEN']
      sh "echo Uploading " + file_name + " to Slack"
      sh "curl https://slack.com/api/files.upload -F token=\""+token+"\" -F channels=\"#converge-codelab-qa\" -F title=\"" + file_name + "\" -F filename=\"" + file_name + "\" -F file=@" + file_path
    end

  after_all do |lane|
    slack(
      message: "successfully deployed new app"
    )
    end

   error do |lane, exception|
    slack(
        message: exception.message,
        success: false
    )
    end
end
